api_key:
  display: 'MailerLite API Key'
  type: text
  read_only: true
forms:
  display: 'Forms'
  instructions: 'Add a row for each form you want to capture subscribers details from'
  type: grid
  mode: stacked
  add_row: 'Add Form'
  fields:
    -
      handle: form
      field:
        display: 'Form'
        instructions: 'Select the form you wish to use'
        type: form
        max_items: 1
        mode: select
        validate: required
        width: 50
    -
      handle: subscriber_group
      field:
        display: 'Subscriber Group'
        instructions: 'MailerLite group to add subscribers to'
        type: subscriber_group
        mode: select
        max_items: 1
        width: 50
    -
      handle: name_field
      field:
        display: 'Name Field'
        instructions: 'Defaults to `name`, if your form uses a different field name change it here'
        type: taggable
        default: name
        width: 50
    -
      handle: email_field
      field:
        display: 'Email Field'
        instructions: 'Defaults to `email`, if your form uses a different field name change it here'
        type: taggable
        default: email
        validate: required
        width: 50
    -
      handle: auto_split_name
      field:
        display: 'Automatically Split Name'
        instructions: 'Split into `name` and `last_name` on <a href="https://app.mailerlite.com" target="_blank">MailerLite</a>, this setting is ignored if you map `last_name` separately'
        type: toggle
        default: true
        width: 100
    -
      handle: marketing_optin_field
      field:
        display: 'Opt-in Field'
        instructions: 'Should be an un-ticked checkbox that conforms to data protection regulations in your region'
        type: taggable
        width: 50
        max_items: 1
    -
      handle: marketing_permissions_fields
      field:
        display: 'Marketing Permissions Field'
        instructions: 'You will need to setup a `marketing_permissions` field on <a href="https://app.mailerlite.com" target="_blank">MailerLite</a>, for more info see <a href="https://help.mailerlite.com/article/show/88106-checkboxes-and-marketing-permissions" target="_blank">this article</a>'
        type: taggable
        width: 50
    -
      handle: mapped_fields
      field:
        mode: table
        reorderable: true
        display: 'Mapped Fields'
        type: grid
        icon: grid
        add_row: 'Add Mapped Field'
        fields:
          -
            handle: subscriber_field
            field:
              display: 'Subscriber Field'
              type: subscriber_field
              mode: select
              validate: required
              width: 50
              max_items: 1
          -
            handle: mapped_form_fields
            field:
              display: 'Form Field(s)'
              type: taggable
              validate: required
              width: 50
